#!/bin/bash
##################################
# HA-Lizard version 2.3.3
##################################
#################################################################################################
#
# HA-Lizard - Open Source High Availability Framework for Xen Cloud Platform and XenServer
#
# Copyright Salvatore Costantino
# ha@pulsesupply.com
#
# This file is part of HA-Lizard.
#
#    HA-Lizard is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    HA-Lizard is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with HA-Lizard.  If not, see <http://www.gnu.org/licenses/>.
#
##################################################################################################
if [ ! $1 ] || [ ! $2 ] || [ ! $3 ]
then

	echo "Process Watcher - Kill Processes that run longer than the passed in Timeout
Usage watcher <command name> <PID> <timeout seconds> <optional log label>

Example: <watcher grep 2233 5> will check for the grep command running on PID 2233
If it has been running for more than 5 seconds, PID 2233 will be killed
When calling watcher from another script, background it with <watcher arg1 arg2 arg3 &>
to avoid delaying the execution of the calling script"
exit 1
fi

PROC_PID=$2
sleep $3 
(
VALIDATE_PROC_PID=`ps -p $PROC_PID | grep "$1" | awk '{ print $4; }'`
if [ $VALIDATE_PROC_PID ]
then
        kill $PROC_PID
        logger -t watcher:$4 "Command: $1 has reached maximum allowable time of $3 SECONDS. KILLING PID: $PROC_PID , PID_NAME: $VALIDATE_PROC_PID"
fi
)  &
