name: Build and Publish SRPM and RPM on Release

on:
  release:
    types: [published] # Trigger when a new release is published

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: ~/rpmbuild
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ACTIONS_RUNNER_DEBUG: true

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up the build environment
      - name: Set Up Build Environment
        run: |
          set -euo pipefail

          # Install required dependencies
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y rpm gh

          # Create rpmbuild directory structure
          echo "Setting up rpmbuild directory structure"
          mkdir -p $BUILD_DIR/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

          # Move spec files into the build structure
          cp -R rpm/SPECS/*.spec $BUILD_DIR/SPECS/

          # Create the source archive
          tar --exclude='./.git' --exclude='./rpm/SPECS' -czf $BUILD_DIR/SOURCES/ha-lizard.tar.gz .
          echo $BUILD_DIR
          ls -R $BUILD_DIR
          find /home/runner/rpmbuild/
          find $BUILD_DIR

      # Step 3: Extract version and release information
      - name: Extract Version and Release
        id: versioning
        run: |
          set -euo pipefail

          # Extract version from the most recent tag
          VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')

          # Count commits to determine the release number
          RELEASE=$(git rev-list --count HEAD)

          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "RELEASE=${RELEASE}" >> $GITHUB_ENV

      # Step 4: Build RPM package
      - name: Build SRPM and RPM Package
        run: |
          set -euo pipefail

          # Replace placeholders in spec files with actual version and release
          sed -i "s/__VERSION__/${VERSION}/g" $BUILD_DIR/SPECS/*.spec
          sed -i "s/__RELEASE__/${RELEASE}/g" $BUILD_DIR/SPECS/*.spec

          # Build the RPM package
          echo $BUILD_DIR
          ls -R $BUILD_DIR
          find /home/runner/rpmbuild/
          find $BUILD_DIR
          rpmbuild -ba $BUILD_DIR/SPECS/*.spec

      # Step 5: Upload RPM and SRPM to the GitHub Release
      - name: Upload SRPM and RPM to GitHub Release
        run: |
          set -euo pipefail

          # Upload binary RPMs
          gh release upload "${{ github.event.release.tag_name }}" $BUILD_DIR/RPMS/**/*.rpm --clobber

          # Upload source RPM
          gh release upload "${{ github.event.release.tag_name }}" $BUILD_DIR/SRPMS/*.src.rpm --clobber
